language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t kienict/docker-react-test -f Dockerfile.dev .

script:
        - docker run -e CI=true kienict/docker-react-test npm run test
