language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t kienict/docker-react-test -f Dockerfile.dev .

script:
        - docker run -e CI=true kienict/docker-react-test npm run test

deploy:
        provider: elasticbeanstalk
        edge: true
        region: "us-east-2"
        app: docker-react-test
        env: "DockerReactTest-env"
        bucket_name: "elasticbeanstalk-us-east-2-408675952856"
        bucket_path: "docker-react-test"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
